FROM node:22
RUN apt-get update && apt-get install -y openssh-server \ 
    tmux \ 
    curl \
    vim \
    net-tools \
    traceroute \
    dnsutils \
    netcat-traditional \
    iputils-ping

RUN npm config set prefix /root/.npm-global
RUN npm install -g @qwen-code/qwen-code@latest @vibe-kit/grok-cli@latest @google/gemini-cli@latest @anthropic-ai/claude-code@latest
RUN echo "PATH=/root/.npm-global/bin:$PATH" >> /root/.bashrc

RUN mkdir /var/run/sshd
# ssh terminals don't pass envs properly
COPY .env /root/.env

# Copy authorized_keys file (to be mounted at runtime)
COPY authorized_keys /root/.ssh/authorized_keys

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]